### ISSUE TITLE
braces for the first css selectors

### ISSUE THREAD

**Issue by RolandNaijuka** [sdras/cssgridgenerator#75]
The braces for the first selector in the created CSS code creates the closing braces at the end of the file instead of closing that first selector

**Comment by pnevares** [comment]
I had noticed this but immediately recognized it as Sass/Less-style nested selectors. But I also understand that it's not accessible to anybody unfamiliar with those tools. Intentional or not I agree that this behavior should change.

**Comment by wlvstv** [comment]
@RolandNaijuka / @pnevares is the issue that you are seeing the div classes nested within the parent like so?
```css
.parent {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  grid-template-rows: repeat(5, 1fr);
  grid-column-gap: 0px;
  grid-row-gap: 0px;
  .div1 { grid-area: 1 / 1 / 4 / 5; }
  .div2 { grid-area: 2 / 5 / 3 / 6; }
  .div3 { grid-area: 2 / 5 / 4 / 6; }
} 
```
are you preferring to see a closed parent with subsequent div line items? like this:
```css
.parent {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  grid-template-rows: repeat(5, 1fr);
  grid-column-gap: 0px;
  grid-row-gap: 0px;
}
.div1 { grid-area: 1 / 1 / 4 / 5; }
.div2 { grid-area: 2 / 5 / 3 / 6; }
.div3 { grid-area: 2 / 5 / 4 / 6; }
```
