### ISSUE TITLE
Consider using grid-template-areas

### ISSUE THREAD

**Issue by notpushkin** [sdras/cssgridgenerator#91]
Hey Sarah, thank you so much for an impressive and really useful project like this!

Have you considered using [`grid-template-areas`][1] for simpler layouts which may make output code more readable, e. g.

```css
.parent {
  display: grid;
  grid-template-columns: 200px 1fr;
  grid-template-rows: 70px 1fr 140px;
  grid-column-gap: 10px;
  grid-row-gap: 0px;
  grid-template-areas: "div1 div1"
                       "div4 div2"
                       "div4 div3";
}

.div1 { grid-area: div1; }
.div2 { grid-area: div2; }
.div3 { grid-area: div3; }
.div4 { grid-area: div4; }
```

Versus:

```css
.parent {
  display: grid;
  grid-template-columns: 200px 1fr;
  grid-template-rows: 70px 1fr 140px;
  grid-column-gap: 10px;
  grid-row-gap: 0px;
}

.div1 { grid-area: 1 / 1 / 2 / 3; }
.div2 { grid-area: 2 / 2 / 3 / 3; }
.div3 { grid-area: 3 / 2 / 4 / 3; }
.div4 { grid-area: 2 / 1 / 4 / 2; }
```

This isn't an option for layouts that have overlapping areas, however.

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas
